Hw04 auth
AndreyMandybura/nodejs-homework-rest-api pull request #3
Opened 2022-02-15 12:13 UTC by AndreyMandybura

ДЗ №4. Проверь пожалуйста.

2022-02-15 20:46 UTC, KirillKulakow commented on routes/api/contacts.js
> +    const skip = (page - 1) * limit;
рекомендую перед математическими операциями выполнять проверку через метод isNaN - так как в query можно передать любую строку

2022-02-15 20:58 UTC, KirillKulakow commented on routes/api/contacts.js
>  const express = require('express')
в данном файле у тебя не все пути защищены
любой юзер (даже не зарегистрированный) может посмотреть/изменить/удалить контакт, причем любой контакт

2022-02-15 20:58 UTC, KirillKulakow requested changes
need fix

2022-02-16 16:31 UTC, AndreyMandybura commented
Добавил проверку на число и мидлвару authenticate на все пути. Посмотри пожалуйста.

2022-02-16 19:35 UTC, KirillKulakow commented on routes/api/contacts.js
>  const express = require('express')
Теперь любой юзер (зарегистрированный) может посмотреть/изменить/удалить любой контакт (в том числе и не свой)
исправь поиск контакта учитывая ид собственника

2022-02-16 19:36 UTC, KirillKulakow requested changes
Need fix

2022-02-17 13:29 UTC, AndreyMandybura commented
Правки. Посмотри пожалуйста.

2022-02-17 20:59 UTC, KirillKulakow approved these changes

2022-02-18 10:59 UTC, merged