Hw05 avatars
AndreyMandybura/nodejs-homework-rest-api pull request #4
Opened 2022-02-18 17:01 UTC by AndreyMandybura

ДЗ №5. Проверь пожалуйста.

2022-02-18 20:14 UTC, KirillKulakow commented on routes/api/auth.js
> +        const avatarURL = gravatar.url(email);
в данный метод добавить опцию протокола для полноценной ссылки на аватарку

2022-02-18 20:15 UTC, KirillKulakow commented on routes/api/users.js
> +        const avatarURL = path.join("avatars", newFileName);
попробуй создать ссылку в виде полноценного URL по типу http://localhost:3000/public/avatars/image.jpg
если при переходе по данной ссылке тебе твое приложение отдаст статику (изображение) значит все ок

2022-02-18 20:17 UTC, KirillKulakow commented on middlewares/upload.js
> +    filename: (req, file, cd) => {
если будет интересно можешь попробовать добавить проверку типа файла
чтобы можно было загрузить только картинку

2022-02-18 20:17 UTC, KirillKulakow requested changes
Need fix

2022-02-21 13:54 UTC, AndreyMandybura commented
Правки. Посмотри пожалуйста. Предлагаю оставить в пути к аватарке id пользователя в названии файла. Будет выглядеть более устрашающе))

2022-02-22 20:05 UTC, KirillKulakow approved these changes

2022-02-23 16:59 UTC, merged